# This is a test config see example_config.yaml for a real world example

monitor:
    type: monitor
    print: on       # turns standard output on or off
    udp: off         # turns udp reporting on or off
    server_address: 192.168.1.166:8014   # address and post 255.255.255.255 for broadcast
    report:
        #- parse      # reports each sentence parsed to data
        - data_log   # reports each log data write
        - device     # allow reports from each device which has report set

bridge:
    name: /dev/ttyUSB1
    type: serial
    origin_tag: ray_
    baud: 38400
    input: to_2000
    outputs:
      - to_processor
      #- to_udp_opencpn

ais:
    name: /dev/ttyUSB3
    type: serial
    baud: 38400
    outputs:
      - to_2000
      #- to_udp_opencpn

compass:
    name: /dev/ttyUSB0
    type: serial
    report: off
    origin_tag: cp_
    outputs:
      - to_processor
      #- to_udp_opencpn
      - to_2000

garmin_gps:
    name: /dev/ttyUSB2
    type: serial
    input: to_vhf
    report: off
    origin_tag: bk_
    outputs:
        - to_processor
        #- to_vhf

udp_opencpn:
    type:  udp_client
    input: to_udp_opencpn
    server_address: 127.0.0.1:8011

udp_compass_listen:
    type:  udp_listen
    origin_tag: esp_
    report: off
    outputs:
        - to_processor
    port: 8008


main_processor:
    type: nmea_processor # Links to any make_sentence types with processor field referring to this processor
    input: to_processor  # NMEA data received will be stored to data base and tagged with origin prefix
                         # if applied by the origin channel
    log_period: 5     # zero means no log saved
    data_retain: 10   # number of seconds before old records are removed
    add_now_var: utc_datetime
    datetime_tags:
        - ray_
        - bkgps_
        - utc_

    processor: main_processor
gps_make:
    type: make_sentence
    every: 1500
    use_origin_tag: ray_ 
    else_origin_tag: bk_ 
    sentence: rmc
    prefix: GP
    outputs:
        - to_vhf
        - to_udp_opencpn




      