# This is a test config see example_config.yaml for a real world example

monitor:
    type: monitor
    server_address: 192.168.1.166:8014

compass_sim:
    name: /dev/ttyUSB1
    type: serial
    input: to_compass

compass:
    name: /dev/ttyUSB0
    type: serial
    origin_tag: cp_
    outputs:
      - to_processor

main_processor:
    type: nmea_processor # Links to any make_sentence types with processor field referring to this processor
    input: to_processor  # NMEA data received will be stored to data base and tagged with origin prefix
                         # if applied by the origin channel
    log_period: 15    # zero means no log saved
    data_retain: 10000   # number of seconds before old records are removed
    add_now_var: utc_datetime
    data_parse:
        - +@sim_@$HCHDM,172.5,M*28
        - +@ray_@$GPAPB,A,A,5,L,N,V,V,359.,T,1,359.1,T,6,T,A*7C
        - +@ray_@$SSDPT,2.8,-0.7
        - +@ray_@$GPRMC,110910.59,A,5047.3986,N,00054.6007,W,0.08,0.19,150920,0.24,W,D,V*75
        # - +@ray_@$GPZDA,110910.59,15,09,2020,00,00*6F 

    datetime_tags:
        - ray_
        - gm_
        - utc_

compass_make:
    type: make_sentence
    processor: main_processor
    every: 200
    use_origin_tag: sim_  
    sentence: hdm
    prefix: HD
    outputs:
        - to_compass


      