
udp_monitor:
    type: udp_monitor
    server_address: 192.168.1.166:8004

compass:
    name: /dev/ttyUSB0
    type: serial
    baud:  4800
    origin_tag: cp_
    outputs:
      - to_processor

gps:_backup:
    name: /dev/ttyUSB2
    type: serial
    baud: 38400
    origin_tag: gm_
    input: to_2000
    outputs:
      - to_processor

bridge:
    name: /dev/ttyUSB1
    type: serial
    origin_tag: ray_
    baud: 38400
    input: to_2000
    outputs:
      - to_processor

ais:
    name: /dev/ttyUSB3
    type: serial
    baud: 38400
    outputs:
      - to_2000
      - to_udp_opencpn

udp_compass_listen:
    type:  udp_listen
    origin_tag: esp_
    outputs:
        - to_processor
    port: 8006


main_processor:
    type: processor
    input: to_processor  # NMEA data received will be stored to data base and tagged with origin prefix
                         # if applied by the origin channel
    log_period: 15   # zero means no log saved
    data_retain: 15  # number of seconds before old records are removed
    outputs:         # this list ensures the channels are created
        - to_2000
        - to_udp_opencpn
        - to_udp_autohelm
    0183_generators:    # routes from database
        hdm:                # Write a hdm message from stored data
            every: 200      # 200ms is minium period between sends
            prefix: HF      # prefix so message generated starts with $HFHDM
            use_origin_tag: cp_        # selects data tagged from esp_ source
            if: 
                - esp_compass_status == 3333  # but only if compass_status is 3333 note must use spaces around ==
                - esp_auto == 1               # and auto == 1
            then_origin_tag: esp_             # selects data tagged from esp_ source
            send_to:
                - to_2000
                - to_udp_opencpn
                - to_udp_autohelm
        rmc:
            every: 15
            prefix: DP
            use_origin_tag: ray_ 
            else_origin_tag: gm     
            send_to:
                - to_udp_opencpn
                - to_2000
        dpt:
            every: 10
            prefix: SD
            use_origin_tag: ray_ 
            send_to:
                - to_udp_opencpn

udp_opencpn:
    type:  udp_client
    input: to_udp_opencpn
    server_address: 192.168.1.14:8011

udp_autohelm:
    type:  udp_client
    input: to_udp_autohelm
    server_address: 127.0.0.0:8007
