
udp_monitor:
    type: udp_monitor
    server_address: 192.168.1.166:8004

compass:
    name: /dev/ttyUSB0
    type: serial
    baud:  4800
    origin_tag: cp_
    outputs:
      - to_processor

bridge:
    name: /dev/ttyUSB1
    type: serial
    origin_tag: ray_
    baud: 38400
    input: to_2000
    outputs:
      - to_processor
      
udp_opencpn:
    type:  udp_client
    input: to_udp_opencpn
    server_address: 192.168.1.14:8011

udp_autohelm:
    type:  udp_client
    input: to_udp_autohelm
    server_address: 127.0.0.0:8007
